### ISSUE TITLE
Generating functions

### ISSUE THREAD

**Issue by gisellemnr** [league/qcheck#6]
Hi,

I noticed that whenever I am using a construction like:

```
zip (arrow (a_cogen, b_gen), list _)
```

the generated list (or any data-structure, even those with my own user-defined generator) have size 0. `arrow` is:

```
fun arrow (cogen, gen) r =
    let val (r1, r2) = split r
        fun g x =
            let val (y,_) = cogen x gen r1
             in y
            end
     in (g, r2)
end
```

If I change the returning `r2` to `r`, then non-trivial data-structures are generated. So upon checking the implementation of `split`, I noticed that for a great majority of cases, the resulting `r0` and `r1` are equal to `0.0`. Is this the intended behaviour? If so, how can I force the generation of non-trivial data-structures?

Thank you!

(PS: I did not have time to investigate further the compilation bug. Since I am using qcheck for a course, I didn't want to mess up the installation during the semester. It all seems to work fine now though :) )

**Comment by gisellemnr** [comment]
Here's a MWE of the behaviour I was talking about.

```
$ sml -m qcheck.cm
- open QCheck;
opening QCheck
   [...]
- val f = Gen.zip (Gen.arrow (Gen.cobool, Gen.Int.int), Gen.list (Gen.flip'(2,8)) Gen.Int.int);
val f = fn : ((bool -> int) * int list) ?.RandGen.gen
- val r = Gen.new ();
val r = 522774926.555 : real
- f r;
val it = ((fn,[]),168045708.633) : ((bool -> int) * int list) * real
- val r = Gen.new ();
val r = 523166366.395 : real
- f r;
val it = ((fn,[]),250044369.887) : ((bool -> int) * int list) * real
- val r = Gen.new ();
val r = 523380007.078 : real
- f r;
val it = ((fn,[]),168525102.046) : ((bool -> int) * int list) * real
```

After changing the `arrow` function as explained above, I get:
```
$ sml -m qcheck.cm
- open QCheck;
opening QCheck
   [...]
- val f = Gen.zip (Gen.arrow (Gen.cobool, Gen.Int.int), Gen.list (Gen.flip'(2,8)) Gen.Int.int);
val f = fn : ((bool -> int) * int list) ?.RandGen.gen
- val r = Gen.new ();
val r = 525855610.918 : real
- f r;
val it = ((fn,[~348490588645628,31258279]),941889744.23)
  : ((bool -> int) * int list) * real
- val r = Gen.new ();
val r = 525978234.438 : real
- f r;
val it =
  ((fn,
    [53684300806003,4586464066,~27330023086,~6730,~6933,~4611686018427387904,
     ~234426155304306,~1395035]),1112750834.06)
  : ((bool -> int) * int list) * real
- val r = Gen.new ();
val r = 526037224.887 : real
- f r;
val it = ((fn,[~377874855992234619,350423120780646355]),1659502387.14)
  : ((bool -> int) * int list) * real
```

I have this fix in a fork. Let me know if you want me to make a pull request.

**Comment by league** [comment]
This is great, thanks for the explanation and contribution! I haven't been using or teaching with SML lately, so I haven't used this in several years, but I'm happy to coordinate fixes and contributions from those who do! 

I will just merge from your branch, no need to create a PR.
